services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    volumes:
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8021:8080

volumes:
  data:
    name: lubelogger-data
  keys:
    name: lubelogger-keys