services:
  # VPN Client Container using Gluetun
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP control server
      - 8080:8080/tcp # qBittorrent Web UI
      - 6881:6881/tcp # qBittorrent TCP
      - 6881:6881/udp # qBittorrent UDP
      - 9696:9696     # Prowlarr UI
    volumes:
      - ${CONFIG_PATH}/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=openvpn
      # Get these from https://account.surfshark.com/vpn/manual-setup
      - OPENVPN_USER=${SURFSHARK_USERNAME}
      - OPENVPN_PASSWORD=${SURFSHARK_PASSWORD}
      # You can change this to a specific location if desired, e.g. 'nl' for Netherlands
      - SERVER_COUNTRIES=Netherlands
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    networks:
      - vpn_network

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${CONFIG_PATH}/docker/jellyfin/config:/config
      - ${MEDIA_SERVER_PATH}/data/media/tv:/data/tv
      - ${MEDIA_SERVER_PATH}/data/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
    networks:
      - vpn_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${CONFIG_PATH}/docker/qb:/config
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/torrents
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  ## Trackers
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Amsterdam
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${CONFIG_PATH}/docker/prowlarr:/config
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  sonarr: # TV
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${CONFIG_PATH}/docker/sonarr:/config
      - ${MEDIA_SERVER_PATH}/data/media/tv:/data/tv
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/torrents
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - vpn_network

  radarr: # Movies
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${CONFIG_PATH}/docker/radarr:/config
      - ${MEDIA_SERVER_PATH}/data/media/movies:/data/movies
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/torrents
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - vpn_network

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/docker/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - vpn_network

networks:
  vpn_network:
    driver: bridge
